### ISSUE TITLE
qmviolin runs with errors

### ISSUE THREAD

**Issue by araikes** [hickst/qmtools#5]
Running `qmviolin` produces an HTML report and pngs but also the following error. It does not matter whether there is a specified report directory or not.

**Environment:**
University of Arizona HPC
Singularity image (pulled from Docker on 2022-03-17 via `singularity pull docker://hickst/qmtools`)

**Call:** 
`singularity exec /groups/adamraikes/singularity_images/qmtools_latest.sif qmviolin T1w fetched/ge_sample.tsv ../mriqc-0.15.1/T1w/group_T1w.tsv -r v0.15.1_violin -v`

**Error:**
```
(qmviolin): Comparing MRIQC records with modality 'T1w'.
Traceback (most recent call last):
  File "/usr/local/bin/qmviolin", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/qmtools/qmviolin/violin_cli.py", line 119, in main
    violin.make_html_report(modality, args, plot_info)
  File "/usr/local/lib/python3.9/site-packages/qmtools/qmviolin/violin.py", line 121, in make_html_report
    copy_tree(genh.AUX_DIR_PATH, report_dirpath)
  File "/usr/local/lib/python3.9/site-packages/qmtools/file_utils.py", line 15, in copy_tree
    shutil.copytree(from_dir, to_dir, dirs_exist_ok=True)
  File "/usr/local/lib/python3.9/shutil.py", line 563, in copytree
    with os.scandir(src) as itr:
FileNotFoundError: [Errno 2] No such file or directory: 'qmtools/qmviolin/static'
```

I think it's only affecting some side bar static images, but I'm not sure:
![image](https://user-images.githubusercontent.com/18663624/159346297-49f9299c-df1a-434f-b521-be632df42e7b.png)

**Comment by hickst** [comment]
QMTools has been updated to run under both Docker and Apptainer (or at the command line via a Python virtual environment, with appropriate setup). The [QMTools Support project](https://github.com/hickst/qmtools-support) has also been enhanced, with new scripts to run the QM tools using Apptainer (by default, on the U of AZ HPC). We highly recommend that you run QMTools through the support project.
