### ISSUE TITLE
Time out errors with qmfetcher

### ISSUE THREAD

**Issue by araikes** [hickst/qmtools#6]
Running `qmfetcher` and get timeout errors (irrespective of number of records). Most of the time I can brute force re-run it and get the data but larger and larger samples become increasingly unlikely. I'm trying to get a sufficiently large sample to be able to figure out how the Manufacturer and Model fields are set for GE Discovery MR750s (if at all available). I successfully ran this with `-n 300` but that took sever tries with this same error.

**Environment:**
University of Arizona HPC
Singularity image (pulled from Docker on 2022-03-17 via `singularity pull docker://hickst/qmtools`)

**Call:** 
`singularity exec /groups/adamraikes/singularity_images/qmtools_latest.sif qmfetcher -v T1w -n 500 -o ge_sample.tsv -q ge.qp`

**Error:**

```
(qmfetcher): Querying MRIQC server with modality 'T1w', for 500 records.
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='mriqc.nimh.nih.gov', port=443): Read timed out.

During handling of the above exception, another exception occurred:

requests.exceptions.ConnectionError: HTTPSConnectionPool(host='mriqc.nimh.nih.gov', port=443): Read timed out.
```

**Comment by hickst** [comment]
The server that we must contact is **very** slow. I've updated the program with two timeouts: the first for simply contacting the server (30 seconds) and the second for getting one batch of results (3 minutes). On today's internet if you can't contact the server in 30 seconds, it's likely that it's down or that network issues exist between you and the server. For the "batch timeout", I'm assuming that 3 minutes is enough to retrieve a "batch" of records (which the server limits to 50). Note, that this doesn't affect how many records you can get in total; as our program will retrieve the number you ask for, in successive batches.
